services:

  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enaa-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/EnaaSkills?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app
    depends_on:
      - db

  app1:
    restart: on-failure
    build:
      context: /Breif
      dockerfile: Dockerfile
    container_name: brief-app
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Breif?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EnaaSkills
    ports:
      - "3306:3306"
    networks:
      - app
    volumes:
      - db_data:/var/lib/mysql
networks:
  app:
    driver: bridge
volumes:
  db_data:
